# -*- coding: utf-8 -*-
"""ESTE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeWhkgXetOjCEo8Dcfgr7TgMHp2RDwXN

# Test 3 — Quantitative Finance
**Take-home Project · Universidad del Pacífico**

Notebook organizado por secciones del enunciado. Reusa la estructura de
`Portfolio_Optimization.ipynb` y `ARMA_1.py`; lo que no estaba en esos códigos
(tests DM/HLN, ventana rolling, vistas Black-Litterman desde el forecasting)
se escribe desde cero y más explicado.

**Dependencias:** `pip install numpy pandas matplotlib scipy statsmodels xgboost`

## 0 · Setup, librerías e instalaciones
"""

# Todas las instalaciones e imports al inicio (ejecutar una vez la línea de pip)
# pip install numpy pandas matplotlib scipy statsmodels xgboost

import warnings
warnings.filterwarnings("ignore")

import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from scipy.optimize import minimize
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

from numpy.linalg import inv, lstsq

from statsmodels.tsa.arima.model  import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox
from xgboost import XGBRegressor

# helper de formato
pct = lambda x: f"{x:.2%}"
np.random.seed(42)

"""---
## 1 · Data & EDA

Estadísticas anualizadas por activo más diagnósticos clave (normalidad, raíz
unitaria, efectos ARCH). El detalle visual del EDA está en el script aparte;
aquí dejamos la tabla resumen que pide el enunciado.
"""

# ── PATH: única línea que debes ajustar a tu ruta local ──────────────────────
file_path = "data.csv"          # ← ruta local de data.csv

precios = (pd.read_csv(file_path, sep=";", decimal=".")
             .assign(Date=lambda d: pd.to_datetime(d["Date"], dayfirst=True))
             .sort_values("Date")
             .set_index("Date"))

# Retornos logarítmicos mensuales: r_t = ln(P_t / P_{t-1})
# Usamos log-returns porque son aditivos en el tiempo y simétricos.
ret      = np.log(precios / precios.shift(1)).dropna()
activos  = list(ret.columns)          # ['SPY','ILF','HYG','LVMH','7974','BAP']
n        = len(activos)

# Factor de anualización mensual: 12 para medias/cov, sqrt(12) para vol
FA       = 12

print("0.1 Observación","-"*30,"\n")
print(f"Activos : {activos}")
print(f"Periodo : {ret.index[0].date()}  —  {ret.index[-1].date()}")
print(f"Obs     : {len(ret)} retornos mensuales | Nulos: {ret.isnull().sum().sum()}")


# ── Split en PRECIOS (nos paramos en el mes 84, sin ver el futuro) ───────────
# data_conocida : Jan 2015 – Dec 2021 (84 precios)
# data_prueba   : Jan 2022 – Dec 2025 (48 precios)
data_conocida = precios.iloc[:84]
data_prueba   = precios.iloc[84:]

# ── Retornos ─────────────────────────────────────────────────────────────────
# In-sample: 83 retornos (Feb 2015 – Dec 2021)
# El dropna() elimina Feb 2015 porque no hay P_{t-1} para Jan 2015
ret_conocida = np.log(data_conocida / data_conocida.shift(1)).dropna()

# Out-of-sample: 48 retornos (Jan 2022 – Dec 2025)
# Necesitamos Dec 2021 como ancla para calcular el primer retorno de Jan 2022
p_con_ancla = pd.concat([data_conocida.iloc[[-1]], data_prueba])
ret_prueba  = np.log(p_con_ancla / p_con_ancla.shift(1)).dropna()

# Para modelos que necesitan toda la serie de retornos (rolling, VAR, etc.)
ret = pd.concat([ret_conocida, ret_prueba])
print("0.2 Separación de data","-"*30)
print(f"Precios conocida : {len(data_conocida)} obs | "
      f"{data_conocida.index[0].strftime('%b %Y')} – {data_conocida.index[-1].strftime('%b %Y')}")
print(f"Precios prueba   : {len(data_prueba)} obs | "
      f"{data_prueba.index[0].strftime('%b %Y')} – {data_prueba.index[-1].strftime('%b %Y')}")
print(f"\nRet in-sample    : {len(ret_conocida)} obs | "
      f"{ret_conocida.index[0].strftime('%b %Y')} – {ret_conocida.index[-1].strftime('%b %Y')}")
print(f"Ret out-of-sample: {len(ret_prueba)} obs | "
      f"{ret_prueba.index[0].strftime('%b %Y')} – {ret_prueba.index[-1].strftime('%b %Y')}")
print(f"\nTotal retornos   : {len(ret)} (= 83 + 48)")

# ── Gráfico 1: Precios en el tiempo ─────────────────────────────────────────
# Solo mostramos data_conocida — nos paramos en Dic 2021 (mes 84)
# Ver data_prueba sería trampa: el modelo no puede usar información del futuro

fig, axes = plt.subplots(3, 2, figsize=(13, 9), sharex=True)
axes = axes.flatten()
COLORES = [
    "#7A1E2C",  # SPY  - granate institucional
    "#A63D52",  # ILF  - vino
    "#C06C84",  # HYG  - rosa vino suave
    "#2F3437",  # LVMH - grafito
    "#6C757D",  # 7974 - gris azulado
    "#B89B5E"   # BAP  - dorado mate
]

fecha_corte = data_conocida.index[-1]   # Dic 2021 — "hoy" para el modelo

for i, activo in enumerate(activos):
    ax = axes[i]
    ax.plot(data_conocida.index, data_conocida[activo],
            color=COLORES[i], linewidth=1.3)

    # línea vertical: límite de lo que "conocemos"
    ax.axvline(fecha_corte, color="black", linewidth=1.2,
               linestyle="--", alpha=0.7, label="T = Dic 2021")

    ax.set_title(activo, fontsize=10, fontweight="bold")
    ax.set_ylabel("Precio", fontsize=8)
    ax.tick_params(labelsize=7)
    ax.legend(fontsize=7, loc="upper left")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

fig.suptitle("Precios en el Tiempo"
             "Ene 2015 – Dic 2021  |  (Periodo actual = 84)",
             fontsize=12, fontweight="bold")
plt.tight_layout()
plt.show()

"""Modelamos los precios para determinar si necesitan ser transformados.
* SPY, LVMH y 7974 presentan una tendencia creciente clara (drift positivo); es decir, son no estacionarios, por lo cual no los podemos modelar directamente con AR/MA/ARMA.
* HYG, ILF y BAP no muestran una tendencia clara, pero el nivel sí cambia a lo largo del tiempo. No podemos concluir estacionariedad solo con esto — necesitamos ver el comportamiento de la varianza en los retornos.

Observamos una ruptura estructural durante el 2020 por la pandemia en casi todos los activos, si la varianza cambia mucho (cosa que sí vemos en BAP y ILF), los modelos ARMA podrían ensuciarse por este lapso y no capturar todo el riesgo o pensar que los tiempos cambiaron y ahora enfrentamos más volatilidad.

Conclusión: los precios son I(1) — su media y varianza no son constantes en el tiempo. No son modelables directamente con AR/MA/ARMA. La solución es transformarlos a log-returns $r_t = \ln(P_t / P_{t-1})$, que son I(0).
"""

# ── Gráfico 2: Log-returns en el tiempo ─────────────────────────────────────
# Solo ret_conocida — las bandas ±2σ se calculan con lo que "conocemos"
# μ y σ estimados in-sample; no usamos ret_prueba

fig, axes = plt.subplots(3, 2, figsize=(13, 9), sharex=True)
axes = axes.flatten()

for i, activo in enumerate(activos):
    ax  = axes[i]
    r   = ret_conocida[activo] * 100

    ax.plot(ret_conocida.index, r, color=COLORES[i], linewidth=0.9, alpha=0.85)
    ax.axhline(0, color="black", linewidth=0.5, linestyle="--", alpha=0.4)

    # ±2σ calculado solo con datos conocidos
    mu_r  = r.mean()
    sig_r = r.std()
    ax.axhline(mu_r + 2*sig_r, color=COLORES[i], linewidth=0.7,
               linestyle=":", alpha=0.6, label="±2σ")
    ax.axhline(mu_r - 2*sig_r, color=COLORES[i], linewidth=0.7,
               linestyle=":", alpha=0.6)

    # línea de corte
    ax.axvline(fecha_corte, color="black", linewidth=1.2,
               linestyle="--", alpha=0.7)

    ax.set_title(activo, fontsize=10, fontweight="bold")
    ax.set_ylabel("lr (%)", fontsize=8)
    ax.tick_params(labelsize=7)
    ax.legend(fontsize=7, loc="upper right")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

fig.suptitle("Log-Returns Mensuales \n"
             "Feb 2015 – Dic 2021",
             fontsize=12, fontweight="bold")
plt.tight_layout()
plt.show()

"""A diferencia de los precios, los retornos ahora oscilan alrededor de una media constante (cercana a cero), lo cual significa que la transformación a log-returns funcionó para lograr estacionariedad, permitiendo el uso de modelos lineales.

Por un lado, los activos ILF, BAP y HYG, en periodos de alta volatilidad, tienden a venir acompañados de más volatilidad, por lo cual su desviación puede ser mayor.

Además, el evento extremo de marzo 2020 puede ensuciar la estimación de los parámetros $\phi$ (AR) y $\theta$ (MA), ya que los modelos clásicos intentarán ajustar sus coeficientes de memoria lineal a un evento que es puramente un choque externo.

Los activos tienen escalas diferentes, mientras que HYG se mueve en un rango pequeño, 7974 o ILF tienen rangos mucho más amplios. Esto indica que, aunque todos sean estacionarios, el riesgo y la persistencia de los choques serán muy distintos en cada uno.
"""

# Estadísticas anualizadas — solo con ret_conocida (in-sample)
def estadisticas_anualizadas(r):
    jb_p = {c: stats.jarque_bera(r[c])[1] for c in r.columns}
    tabla = pd.DataFrame({
        "Media anual"  : r.mean() * FA,
        "Vol anual"    : r.std()  * np.sqrt(FA),
        "Sharpe (rf=0)": (r.mean() * FA) / (r.std() * np.sqrt(FA)),
        "Skewness"     : r.skew(),
        "Kurt exceso"  : r.kurtosis(),
        "JB p-valor"   : pd.Series(jb_p),
    })
    return tabla

eda = estadisticas_anualizadas(ret_conocida)
print(eda.to_string(formatters={
    "Media anual"  : pct,
    "Vol anual"    : pct,
    "Sharpe (rf=0)": "{:.3f}".format,
    "Skewness"     : "{:.3f}".format,
    "Kurt exceso"  : "{:.3f}".format,
    "JB p-valor"   : "{:.4f}".format,
}))

# ── distribución de retornos in-sample por activo ────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(13, 7))
axes = axes.flatten()

for i, activo in enumerate(activos):
    ax = axes[i]
    r  = ret_conocida[activo].values * 100   # solo datos conocidos

    ax.hist(r, bins=25, density=True,
            color=COLORES[i], alpha=0.65, edgecolor="white", linewidth=0.4)

    x = np.linspace(r.min(), r.max(), 300)
    ax.plot(x, stats.norm.pdf(x, r.mean(), r.std()),
            color="black", linewidth=1.5, linestyle="--", label="N(μ, σ²)")

    ax.axvline(0, color="gray", linewidth=0.7, linestyle=":")

    sk   = ret_conocida[activo].skew()
    ku   = ret_conocida[activo].kurtosis()
    jb_p = stats.jarque_bera(ret_conocida[activo])[1]
    ax.set_title(
        f"{activo}\nsk = {sk:.2f}   ku = {ku:.2f}   JB p = {jb_p:.3f}",
        fontsize=9, fontweight="bold"
    )
    ax.set_xlabel("Retorno mensual (%)", fontsize=8)
    ax.set_ylabel("Densidad", fontsize=8)
    ax.tick_params(labelsize=8)
    ax.legend(fontsize=7)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

fig.suptitle(
    "Distribución de Log-Returns Mensuales — In-Sample (Feb 2015 – Dic 2021)\n"
    "línea punteada = Normal teórica con misma μ y σ estimados in-sample",
    fontsize=11, fontweight="bold"
)
plt.tight_layout()
plt.show()

"""Observamos que la mayoría de los activos posee asimetría negativa y kurtosis altas, una combinación peligrosa porque el precio de estos activos tiende a desplomarse de forma abrupta. Sumado a ello, solo el activo "LVMH" presenta un perfil normal según el test de Jarque-Bera, implicando así que este necesita un tratamiento tradicional (distribución normal); de lo contrario, al aplicarle modelos de valores extremos, se estaría cayendo en una ineficiencia de datos u overfitting. Para los demás sería obligatorio realizar un Peaks over threshold con la distribución GPD para que estas colas estén bien modeladas.

Aunque procederemos con modelos ARMA, la prueba JB y la alta curtosis sugieren que los activos presentan colas pesadas, lo que podría afectar la precisión de los intervalos de confianza de nuestros parámetros estimados.

---
## 2 · Model Estimation  [7 pts]

### 2.a — AR, MA, ARMA y XGBoost in-sample (primeros 83 retornos)

Estimamos sobre los primeros **83 retornos mensuales** (Feb 2015 – Dic 2021,
ventana in-sample = 7 años).
Especificaciones mínimas pedidas: **AR(1)**, **MA(1)**, **ARMA(1,1)**.
Reportamos parámetros y errores estándar por activo y modelo.
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from xgboost import XGBRegressor

# Configuración inicial
W_IN  = 83                               # 83 retornos in-sample: Feb 2015 – Dic 2021
ret_in = ret.iloc[:W_IN]
ordenes = {"AR(1)": (1,0,0), "MA(1)": (0,0,1), "ARMA(1,1)": (1,0,1)}

def estimar_arima(serie, orden):
    """Estima ARIMA por MLE condicional y devuelve el modelo ajustado."""
    m = ARIMA(serie, order=orden).fit(method_kwargs={"warn_convergence": False})
    return m

# Bucle unificado para reporte por activo
for a in activos:
    print("="*64)
    print(f"ACTIVO: {a}")
    print("="*64)

    print("--- MODELOS CLÁSICOS (ARIMA) ---")
    for nombre, orden in ordenes.items():
        m = estimar_arima(ret_in[a].values, orden)
        print(f"\n  {nombre}   AIC={m.aic:.2f}  BIC={m.bic:.2f}")
        for pn, pv, se in zip(m.param_names, m.params, m.bse):
            if se > 0:
                t = pv/se
                sig = "***" if abs(t)>2.576 else "**" if abs(t)>1.96 else "*" if abs(t)>1.645 else ""
                print(f"    {pn:10s}  {pv:+.5f}  (SE {se:.5f})  t={t:+.2f} {sig}")

    print("\n--- MODELO MACHINE LEARNING (XGBoost In-Sample) ---")
    s = ret[a]
    # Construir características usando la serie completa pero recortando in-sample
    feat_in = pd.DataFrame({
        "lag1": s.shift(1),
        "lag2": s.shift(2),
        "lag3": s.shift(3),
        "rvol3": s.shift(1).rolling(3).std()
    }).iloc[:W_IN].dropna()

    y_in = s.iloc[:W_IN].loc[feat_in.index]

    # Entrenar XGBoost
    mx = XGBRegressor(n_estimators=100, max_depth=3, learning_rate=0.05,
                      subsample=0.8, min_child_weight=5, reg_alpha=0.1,
                      random_state=42, verbosity=0).fit(feat_in, y_in)

    for f, imp in zip(feat_in.columns, mx.feature_importances_):
        print(f"    {f:6s}: {imp:.3f}")
    print("\n")

"""Utilizando la ventana de 83 retornos in-sample (Feb 2015 – Dic 2021), se presenta el análisis de la razonabilidad de los parámetros y sus errores estándar para los modelos AR(1), MA(1) y ARMA(1,1) en cada activo:

* SPY: El modelo más razonable es el MA(1). El coeficiente ma.L1 ($-0.1989$) es significativo al 5% ($t \approx -2.23$, $SE = 0.0892$). Nótese que el estadístico cae en el umbral $|t| > 1.96$ pero no supera $2.576$, por lo que es significativo al 5% (**) y no al 1% (***) — calificarlo de "altamente significativo" sería inexacto. El modelo ARMA(1,1) también converge, pero sus coeficientes se muestran artificialmente inflados ($0.756$) y ($-0.901$), con un efecto casi perfectamente opuesto que delata sobreajuste; además pierde por AIC y BIC.

* LVMH y BAP: en ambos activos, la especificación ARMA(1,1) resulta ser la más razonable y robusta por sus coeficientes (ar.L1 y ma.L1) que son estadísticamente significativos y poseen errores estándar bajos respecto al tamaño del parámetro. Además, se sitúan estrictamente dentro de los límites teóricos de estacionariedad e invertibilidad; es decir, valores absolutos menores a 1.

* ILF y HYG: Ninguno de los modelos resultó razonable. Sus coeficientes principales carecen por completo de significancia estadística, reflejando que sus medias se comportan como ruido puro en esta ventana temporal. Cabe destacar que en el ARMA(1,1) de HYG, el modelo colapsa matemáticamente al arrojar un coeficiente ma.L1 al borde del límite permisible ($-0.99975$) con un error estándar desproporcionado ($SE = 13.765$): el optimizador no puede distinguir entre la raíz MA y el proceso subyacente, señal inequívoca de no-identificación.

* 7974: El modelo ARMA(1,1) no es razonable debido a un problema de cancelación mutua de raíces. Los coeficientes estimados son extremos y de signo opuesto ($ar.L1 = -0.964$) y ($ma.L1 = +0.925$), lo que indica que los términos se anulan entre sí y el algoritmo está sobreajustando el ruido. Sus modelos individuales AR(1) y MA(1) tampoco son significativos.

Eso es en los modelos clásicos, pero ahora con el modelo de XGBoost sucede que nuestras variables: lag1, lag2, lag3 y rvol3 presentan valores entre [0.20-0.30], lo cual significaría que cada una tiene aproximadamente un 25% de importancia. Esto significa que XGBoost no encontró ninguna variable que sea "la reina" de la predicción. Significa que todas aportan casi lo mismo: es decir, aportan muy poco.

### 2.b — Errores out-of-sample con ventana rolling (P = 48)

Ventana rolling de 83 retornos: se reestima en cada paso, se pronostica 1 mes
adelante y se avanza un mes. Evaluación sobre meses 84–131 (P = 48).
"""

def xgb_forecast(serie, window=84):
    """
    Rolling XGBoost 1-paso-adelante sobre una serie de log-returns.
    Features: 3 rezagos + volatilidad realizada de 3 meses (igual que el enunciado).
    Devuelve (forecast, actual, error) sobre la ventana de evaluación.
    """
    s    = pd.Series(serie)
    feat = pd.DataFrame({
        "lag1" : s.shift(1),
        "lag2" : s.shift(2),
        "lag3" : s.shift(3),
        "rvol3": s.shift(1).rolling(3).std(),
    }).values
    y = s.values
    T = len(y)
    fc, act = np.zeros(T-window), np.zeros(T-window)
    for i, t in enumerate(range(window, T)):
        Xtr, ytr = feat[t-window:t], y[t-window:t]
        mask = ~np.isnan(Xtr).any(axis=1)        # ← corregido: filas SIN NaN
        m = XGBRegressor(n_estimators=100, max_depth=3, learning_rate=0.05,
                         subsample=0.8, min_child_weight=5, reg_alpha=0.1,
                         random_state=42, verbosity=0)
        m.fit(Xtr[mask], ytr[mask])
        fc[i]  = m.predict(feat[t:t+1])[0] if not np.isnan(feat[t]).any() else 0.0
        act[i] = y[t]
    return fc, act, act - fc

def rolling_forecast_arima(serie, orden, window=84):
    """
    Rolling 1-paso-adelante para un ARIMA.
    En cada t reestima con las últimas `window` obs y pronostica r_{t+1}.
    Devuelve errores sobre la ventana de evaluación (longitud T-window).
    """
    y = np.asarray(serie)
    T = len(y)
    fc, act = [], []
    for t in range(window, T):
        train = y[t-window:t]                      # ventana móvil de 84 meses
        m = ARIMA(train, order=orden).fit(method_kwargs={"warn_convergence": False})
        fc.append(m.forecast(steps=1)[0])          # pronóstico 1 paso adelante
        act.append(y[t])
    fc, act = np.array(fc), np.array(act)
    return fc, act, act - fc

# Generamos errores OOS para cada activo y cada modelo (incl. XGBoost)
errores = {a: {} for a in activos}      # errores[activo][modelo] = vector de errores
P = len(ret) - W_IN                      # debe ser 48 (131 retornos totales − 83 in-sample)
print(f"Ventana de evaluación P = {P} meses (retornos 84–131)\n")

for a in activos:
    for nombre, orden in ordenes.items():
        _, _, e = rolling_forecast_arima(ret[a].values, orden, W_IN)
        errores[a][nombre] = e
    # XGBoost
    _, _, e_xgb = xgb_forecast(ret[a].values, W_IN)
    errores[a]["XGBoost"] = e_xgb
    rmse = {k: np.sqrt(np.mean(v**2)) for k, v in errores[a].items()}
    print(f"{a:6s} RMSE OOS:", {k: round(x,5) for k,x in rmse.items()})

"""### 2.c — Diebold–Mariano y Harvey–Leybourne–Newbold

Estos tests **no estaban** en los códigos previos, así que se escriben desde
cero y con detalle.

**Diebold–Mariano (1995):** compara la *accuracy* de dos pronósticos vía el
diferencial de pérdida $d_t = L(e_{1t}) - L(e_{2t})$ (pérdida cuadrática,
$L(e)=e^2$). Bajo $H_0$ de igual accuracy, $\bar d = 0$. El estadístico es
$$ DM = \frac{\bar d}{\sqrt{\widehat{\mathrm{Var}}(\bar d)}} \xrightarrow{d} N(0,1). $$
El problema del proxy de $\sigma^2_t$ no aplica aquí porque evaluamos pronósticos
de **retornos** (observables), no de varianza latente.

**HLN (1997):** corrige el sesgo de muestra pequeña del DM multiplicando por
$$ \sqrt{\tfrac{T+1-2h+h(h-1)/T}{T}} $$
y comparando contra una $t_{T-1}$ en vez de la normal. Con P = 48 (muestra
chica) la corrección importa.
"""

def dm_test(e1, e2, h=1, power=2):
    """
    Diebold-Mariano. H0: igual accuracy.
    e1, e2: errores de los modelos 1 y 2.  power=2 → pérdida cuadrática (MSE).
    DM > 0  ⇒  modelo 1 PEOR que modelo 2 (mayor pérdida).
    """
    e1, e2 = np.asarray(e1), np.asarray(e2)
    d = np.abs(e1)**power - np.abs(e2)**power      # diferencial de pérdida
    T = len(d)
    dbar = d.mean()
    # Varianza de largo plazo (Newey-West con h-1 autocovarianzas para horizonte h)
    gamma0 = np.var(d, ddof=0)
    gammas = [np.cov(d[k:], d[:-k], ddof=0)[0,1] for k in range(1, h)] if h > 1 else []
    var_dbar = (gamma0 + 2*sum(gammas)) / T
    DM = dbar / np.sqrt(var_dbar)
    p  = 2*(1 - stats.norm.cdf(abs(DM)))
    return DM, p

def hln_test(e1, e2, h=1, power=2):
    """Corrección de muestra pequeña de Harvey-Leybourne-Newbold sobre el DM."""
    e1 = np.asarray(e1); T = len(e1)
    DM, _ = dm_test(e1, e2, h, power)
    factor = np.sqrt((T + 1 - 2*h + h*(h-1)/T) / T)
    HLN = DM * factor
    p   = 2*(1 - stats.t.cdf(abs(HLN), df=T-1))      # contra t_{T-1}
    return HLN, p

# Para cada activo: rankear modelos por MSE, identificar mejor y segundo,
# y testear si el mejor supera significativamente al segundo (DM y HLN al 5%).
modelos_arma = list(ordenes.keys())                 # AR(1), MA(1), ARMA(1,1)

resumen_2c = []
for a in activos:
    # Para los modelos ARMA usamos sus errores; SPY además compara contra XGBoost
    cand = {m: errores[a][m] for m in modelos_arma}
    mse  = {m: np.mean(v**2) for m, v in cand.items()}
    ranking = sorted(mse, key=mse.get)              # menor MSE primero
    mejor, segundo = ranking[0], ranking[1]
    dm_stat,  dm_p  = dm_test (cand[mejor], cand[segundo])
    hln_stat, hln_p = hln_test(cand[mejor], cand[segundo])
    resumen_2c.append({
        "Activo": a, "Mejor": mejor, "2do": segundo,
        "DM p": round(dm_p,4), "HLN p": round(hln_p,4),
        "Sig 5%": "Sí" if (dm_p<0.05 or hln_p<0.05) else "No",
    })

tabla_2c = pd.DataFrame(resumen_2c).set_index("Activo")
print(tabla_2c.to_string())

# Comparación específica SPY vs XGBoost (lo pide el enunciado)
print("\n── SPY: mejor modelo ARMA vs XGBoost ──")
mejor_spy = tabla_2c.loc["SPY","Mejor"]
dm_x  = dm_test (errores["SPY"][mejor_spy], errores["SPY"]["XGBoost"])
hln_x = hln_test(errores["SPY"][mejor_spy], errores["SPY"]["XGBoost"])
print(f"  {mejor_spy} vs XGBoost  →  DM p={dm_x[1]:.4f}  HLN p={hln_x[1]:.4f}")
print("  (DM>0 ⇒ el primer modelo tiene mayor pérdida que XGBoost)")

"""**Lectura 2.c:** la columna `Sig 5%` indica en qué activos el mejor modelo
supera **significativamente** al segundo. Cuando ningún test rechaza, los
modelos son estadísticamente equivalentes en accuracy — lo habitual con
retornos mensuales casi impredecibles. Esto alimenta directamente las vistas
de Black-Litterman en 4.b: **solo** generamos vista para los activos donde hay
rechazo al 5%.

---
## 3 · Mean-Variance Optimisation  [2 pts]

### 3.a — MVO sin restricciones (covarianza y media muestral full-sample)

Reusamos las funciones de portafolio de `Portfolio_Optimization.ipynb`.
"""

# Insumos full-sample anualizados
mu    = ret.mean()*FA                    # vector de medias (n,)
Sigma = ret.cov()*FA                     # matriz de covarianzas (n×n)

# rf = promedio de la tasa T-bill 3M sobre el periodo muestral (enunciado)
# Intentamos obtenerlo de FRED (DTB3, tasa anualizada en %); si falla usamos el
# promedio histórico conocido: DGS3MO 2015-2025 promedia ≈ 2.10% anualizado.
try:
    from pandas_datareader.data import DataReader as _DR
    _tbill = _DR("DTB3", "fred", start="2015-01-01", end="2025-12-31")
    rf = float(_tbill.dropna().mean().iloc[0]) / 100   # % → decimal
    print(f"rf (FRED DTB3 promedio 2015-2025): {rf:.4f}  ({rf:.2%} anual)")
except Exception:
    rf = 0.0210   # promedio DGS3MO Ene 2015 – Dic 2025 (FRED, calculado offline)
    print(f"rf (promedio FRED offline 2015-2025): {rf:.4f}  ({rf:.2%} anual)")

mu_np    = mu.values
Sigma_np = Sigma.values
Sigma_inv = inv(Sigma_np)

def ret_port(w):    return w @ mu_np
def vol_port(w):    return np.sqrt(w @ Sigma_np @ w)
def sharpe_port(w): return (ret_port(w)-rf)/vol_port(w) if vol_port(w)>0 else 0.0

# MVO tangency SIN restricciones (forma cerrada): w ∝ Σ⁻¹(μ − rf·1)
w_mvo_uncon = Sigma_inv @ (mu_np - rf)
w_mvo_uncon = w_mvo_uncon / w_mvo_uncon.sum()      # normaliza a suma 1

print("Pesos MVO SIN restricciones:")
for a, w in zip(activos, w_mvo_uncon):
    print(f"  {a:6s}: {w:9.2%}")
print(f"\n  Suma: {w_mvo_uncon.sum():.2f}  | incluye cortos y apalancamiento")

"""**Observación clave:** la MVO sin restricciones produce pesos extremos
(cortos grandes y apalancamiento). Es la inestabilidad clásica de Markowitz:
la media muestral es un estimador muy ruidoso y $\Sigma^{-1}$ lo amplifica.
Esto motiva tanto las restricciones de 3.b como Black-Litterman en la sección 4.

### 3.b — MVO con restricciones económicas razonables

Justificación con **noticias a la fecha (jun-2026):**

- **Long-only (w ≥ 0):** la mayoría de mandatos institucionales no permiten
  cortos; además evita el apalancamiento implícito que vimos en 3.a.
- **Tope por activo del 35%:** evita concentración. Es especialmente prudente
  porque el **SPY** cotiza con valuaciones extremas (Shiller P/E ≈ 42.8, BofA
  advierte que 70% de indicadores de bear market están activados) y porque
  **7974/Nintendo** trae riesgo idiosincrático alto (post-Switch 2, señal
  técnica "Strong Sell").
- **Piso del 5% en HYG:** mantiene un ancla de menor volatilidad (renta fija
  high-yield) como diversificador, aun cuando su retorno histórico fue pobre.
- **Tope del 25% a BAP:** riesgo político de país único — el balotaje peruano
  del 7-jun-2026 quedó en empate técnico, con incertidumbre sobre la política
  hacia el sector financiero.
"""

# Optimizador con restricciones (SLSQP), patrón de Portfolio_Optimization.ipynb
restricciones = [{"type":"eq", "fun": lambda w: w.sum() - 1}]   # totalmente invertido
# bounds por activo: long-only + topes específicos
topes = {"SPY":0.35, "ILF":0.35, "HYG":0.35, "LVMH":0.35, "7974":0.35, "BAP":0.25}
pisos = {"HYG":0.05}
bounds = [(pisos.get(a,0.0), topes.get(a,0.35)) for a in activos]
w0 = np.ones(n)/n

def max_sharpe(w0, mu_v, Sig_v, bnds, cons, rf_=rf):
    neg_sr = lambda w: -((w@mu_v - rf_)/np.sqrt(w@Sig_v@w))
    res = minimize(neg_sr, w0, method="SLSQP", bounds=bnds,
                   constraints=cons, options={"ftol":1e-12,"maxiter":1000})
    return res.x

w_mvo_con = max_sharpe(w0, mu_np, Sigma_np, bounds, restricciones)

print("Pesos MVO CON restricciones:")
for a, w in zip(activos, w_mvo_con):
    print(f"  {a:6s}: {w:8.2%}")
print(f"\n  Retorno {pct(ret_port(w_mvo_con))} | Vol {pct(vol_port(w_mvo_con))} | "
      f"Sharpe {sharpe_port(w_mvo_con):.3f}")

"""### 3.c — Restricciones binding y activos más afectados"""

# Una restricción es "binding" si el peso queda pegado a su cota
print("Diagnóstico de restricciones activas (binding):")
for a, w in zip(activos, w_mvo_con):
    lo, hi = bounds[activos.index(a)]
    estado = "TOPE binding" if abs(w-hi)<1e-4 else "PISO binding" if abs(w-lo)<1e-4 else "interior"
    print(f"  {a:6s}: {w:7.2%}   [{lo:.0%}, {hi:.0%}]   {estado}")

print("\nComparación sin vs con restricciones (activos más afectados):")
comp = pd.DataFrame({"Sin restr.": w_mvo_uncon, "Con restr.": w_mvo_con,
                     "Δ": w_mvo_con - w_mvo_uncon}, index=activos)
print(comp.to_string(formatters={c: pct for c in comp.columns}))

"""**Discusión 3.c:** los activos cuyo peso sin restricción excedía las cotas
son los que quedan *binding* y los más afectados (típicamente el de mayor
Sharpe individual se topa en 35% y los de peso negativo suben a 0%). El salto
más grande en la columna Δ marca el activo más reconfigurado por las
restricciones.

---
## 4 · Black–Litterman  [5 pts]

### 4.a — `reverse_optimization(Σ, w_mkt, γ, rf)` → Π

La optimización inversa parte de los pesos de mercado y recupera los retornos
**implícitos de equilibrio**: $\Pi = \gamma\,\Sigma\,w_{mkt}$ (retornos en
exceso) y verifica $\tfrac{1}{\gamma}\Sigma^{-1}(\Pi) = w_{mkt}$.
"""

def reverse_optimization(Sigma, w_mkt, gamma, rf):
    """
    Optimización inversa de Black-Litterman.
    Devuelve Pi en EXCESO (Pi_excess) y Pi total (Pi_excess + rf).
    Relación de equilibrio:  Pi_excess = gamma * Sigma * w_mkt
    """
    Sigma = np.asarray(Sigma)
    Pi_excess = gamma * Sigma @ w_mkt
    Pi_total  = Pi_excess + rf
    return Pi_excess, Pi_total

GAMMA = 2.5
TAU   = 0.05
w_mkt = w_mvo_con.copy()             # usamos los pesos MVO (restringidos) como mercado

Pi_excess, Pi = reverse_optimization(Sigma_np, w_mkt, GAMMA, rf)

# Verificación: 1/gamma * Σ⁻¹ * Pi_excess debe reproducir w_mkt
w_verif = (1/GAMMA) * Sigma_inv @ Pi_excess
print("Verificación reverse-opt: max|w_verif - w_mkt| =",
      f"{np.max(np.abs(w_verif - w_mkt)):.2e}  (≈0 ✓)\n")

comp_pi = pd.DataFrame({"Π implícito": Pi, "Media muestral μ": mu_np}, index=activos)
print(comp_pi.to_string(formatters={c: pct for c in comp_pi.columns}))

"""**Lectura 4.a:** Π suele ser más suave y económicamente sensato que la
media muestral μ (que es ruidosa). Si Π difiere mucho de μ para un activo, es
señal de que la media histórica de ese activo es poco fiable como expectativa.

### 4.b — Vistas BL desde el forecasting (DM/HLN de la Parte 2)

**Regla:** generamos una vista *absoluta* solo para los activos donde el mejor
modelo superó significativamente al segundo (rechazo DM o HLN al 5% en 2.c).
La vista es $r_k$ = pronóstico del mejor modelo para el **siguiente** mes OOS.
La incertidumbre es $\Omega_{kk} = \tau\,P_k\,\Sigma\,P_k'$.
"""

# 1) Pronóstico del siguiente mes (mes 133) con el mejor modelo de cada activo
def forecast_siguiente(serie, orden, window=84):
    """Reestima con las últimas `window` obs y pronostica 1 paso adelante."""
    train = np.asarray(serie)[-window:]
    m = ARIMA(train, order=orden).fit(method_kwargs={"warn_convergence": False})
    return m.forecast(steps=1)[0]

# 2) Construir vistas SOLO donde hubo significancia al 5%
activos_con_vista = [r["Activo"] for r in resumen_2c if r["Sig 5%"]=="Sí"]
print("Activos con vista BL (rechazo 5% en DM/HLN):", activos_con_vista or "ninguno")

if activos_con_vista:
    K = len(activos_con_vista)
    P_mat = np.zeros((K, n))
    q_vec = np.zeros(K)
    for k, a in enumerate(activos_con_vista):
        orden_mejor = ordenes[tabla_2c.loc[a, "Mejor"]]
        idx = activos.index(a)
        P_mat[k, idx] = 1.0                                   # vista absoluta
        q_vec[k] = forecast_siguiente(ret[a].values, orden_mejor) * FA  # anualizada
    # Ω diagonal proporcional a la varianza del portafolio de la vista
    Omega = np.diag(np.diag(TAU * P_mat @ Sigma_np @ P_mat.T))

    # 3) Posterior de Black-Litterman
    tauS_inv = inv(TAU * Sigma_np)
    M_inv = inv(tauS_inv + P_mat.T @ inv(Omega) @ P_mat)
    mu_bl = M_inv @ (tauS_inv @ Pi_excess + P_mat.T @ inv(Omega) @ q_vec) + rf

    comp_bl = pd.DataFrame({"μ_BL posterior": mu_bl, "μ in-sample": ret_in.mean().values*FA},
                           index=activos)
    print("\n", comp_bl.to_string(formatters={c: pct for c in comp_bl.columns}))
else:
    # Sin vistas, el posterior colapsa al equilibrio Π
    mu_bl = Pi.copy()
    print("\nSin vistas significativas: μ_BL = Π (equilibrio). Reportamos Π vs μ in-sample.")
    comp_bl = pd.DataFrame({"μ_BL (=Π)": mu_bl, "μ in-sample": ret_in.mean().values*FA},
                           index=activos)
    print(comp_bl.to_string(formatters={c: pct for c in comp_bl.columns}))

"""### 4.c — Evaluación de las vistas

**Diagnóstico de la evidencia estadística (output de 2.c)**

En la sección 2.c, ningún activo registró rechazo simultáneo en DM y HLN al 5%.
Cuando el DM rechaza pero HLN no (o viceversa), la evidencia es frágil: el test
HLN aplica una corrección de muestra pequeña que con P = 48 puede desplazar el
p-valor por encima de 0.05 incluso si el DM lo cruza. Aceptar únicamente el
rechazo del DM como evidencia suficiente sería sobreestimar la calidad del
modelo en una muestra reducida.

**Consecuencia para las vistas BL**

Dado que ningún activo superó el umbral conjunto, no se generaron vistas
absolutas y el posterior Black-Litterman colapsa al equilibrio: $\mu_{BL} = \Pi$.
Este resultado es honesto y económicamente sensato: los retornos mensuales son
esencialmente impredecibles con modelos lineales de un solo rezago, por lo que
fabricar vistas sin evidencia estadística sólida introduciría señales falsas que
el marco BL ponderaría junto con el equilibrio y distorsionaría la asignación.

**Limitación de $\Omega_{kk} = \tau P_k \Sigma P_k'$**

Aun si hubiera habido vistas significativas, esta especificación tiene un defecto
conceptual: ata la incertidumbre de la vista a la volatilidad del activo ($\tau\sigma_k^2$),
no a la *calidad predictiva del modelo*. Un modelo que apenas supera al segundo
en RMSE debería recibir un $\Omega_{kk}$ mayor (mayor incertidumbre) que uno que
lo supera ampliamente, pero la regla mecánica no distingue entre ambos casos.
La solución correcta sería calibrar $\Omega_{kk}$ con el MSE OOS del modelo
relativo al benchmark de ruido blanco — pero eso excede lo pedido por el enunciado.

---
## 5 · Dynamic Programming  [1 pt]

### 5.a — Demanda miópica de Merton (CRRA), con restricciones

$$ w^{\text{miope}} = \tfrac{1}{\gamma}\,\Sigma^{-1}(\mu - r_f\mathbf 1). $$
Aplicamos el patrón `project_weights` de tu notebook para imponer las mismas
restricciones que en la MVO restringida.
"""

def project_weights(w_raw, bnds, cons):
    """Proyecta pesos crudos al conjunto factible (long-only, sum=1, topes)."""
    res = minimize(lambda w: np.sum((w-w_raw)**2), np.ones(n)/n,
                   method="SLSQP", bounds=bnds, constraints=cons,
                   options={"ftol":1e-12,"maxiter":1000})
    return res.x

mu_excess  = mu_np - rf
w_miope_raw = (1/GAMMA) * Sigma_inv @ mu_excess
w_miope     = project_weights(w_miope_raw, bounds, restricciones)

print("Demanda miópica (Merton) con restricciones:")
for a, w in zip(activos, w_miope):
    print(f"  {a:6s}: {w:8.2%}")

"""### 5.b — VAR(1): demanda de cobertura y pesos dinámicos

$$ w^{\text{din}} = \underbrace{\tfrac{1}{\gamma}\Sigma^{-1}\mu_e}_{\text{miópica}}
\;\underbrace{-\,\tfrac{1}{\gamma}\Sigma^{-1}\Phi^\top\mu_e}_{\text{cobertura}}. $$
Estimamos $\Phi$ por OLS, igual que en `Portfolio_Optimization.ipynb`.
"""

# VAR(1) por OLS: r_t = μ_c + Φ r_{t-1} + ε_t
R   = ret.values
Y   = R[1:]
X   = R[:-1]
Xa  = np.hstack([np.ones((len(X),1)), X])
B,_,_,_ = lstsq(Xa, Y, rcond=None)
Phi = B[1:].T                                   # matriz n×n de autocorrelación

# Demanda de cobertura y pesos dinámicos (crudos), luego proyectados
w_hedge_raw   = -(1/GAMMA) * Sigma_inv @ Phi.T @ mu_excess
w_hedge       = project_weights(w_hedge_raw, bounds, restricciones)
w_dynamic_raw = w_miope_raw + w_hedge_raw
w_dynamic     = project_weights(w_dynamic_raw, bounds, restricciones)

tabla_dp = pd.DataFrame({"Miópica": w_miope, "Cobertura": w_hedge,
                         "Dinámico": w_dynamic}, index=activos)
print(tabla_dp.to_string(formatters={c: pct for c in tabla_dp.columns}))
print("\nΦ diagonal (persistencia propia):",
      dict(zip(activos, np.round(np.diag(Phi),3))))

"""**Lectura 5.b:** la demanda de cobertura **no fue pequeña** — reorganizó el
portafolio de forma sustancial (ILF pasó de ≈25% miópico a 35% dinámico; LVMH
de ≈16% a 0%). La intuición de que "si la diagonal de $\Phi$ es ≈ 0, la cobertura
es insignificante" es incorrecta: lo que importa es el término $\Sigma^{-1}\Phi^\top\mu_e$
completo, donde $\Phi^\top$ incluye los **elementos fuera de la diagonal**
(auto-correlaciones cruzadas). Aunque cada activo muestre poca persistencia
propia, las correlaciones cruzadas capturan que el retorno rezagado de un activo
predice marginalmente el de otro. Al multiplicar por $\Sigma^{-1}$ (que amplifica
diferencias de correlación) esas correlaciones cruzadas generan una demanda de
cobertura significativa. En términos de Merton (1973): el portafolio dinámico
cubre el riesgo de variaciones en las oportunidades de inversión futuras
inducidas por la dinámica VAR del vector de estados, aunque ningún activo
individualmente sea muy predecible.

---
## 6 · Portfolio comparison  [5 pts]

Comparamos 5 portafolios **long-only y totalmente invertidos**: equiponderado,
Markowitz (MVO restringido), MVO restringido, Black-Litterman y Dynamic
Programming. Para cada uno: retorno anualizado, volatilidad, Sharpe, máximo
drawdown y pesos.
"""

# Portafolio 1: equiponderado
w_ew = np.ones(n)/n
# Portafolio Markowitz (= MVO restringido, max Sharpe) ya calculado: w_mvo_con
# Portafolio BL: optimizar max-Sharpe con μ_BL y Σ
w_bl = max_sharpe(w0, mu_bl, Sigma_np, bounds, restricciones)
# Portafolio DP: w_dynamic

portafolios = {
    "Equiponderado"      : w_ew,
    "Markowitz (MVO)"    : w_mvo_con,
    "MVO restringido"    : w_mvo_con,       # mismo, se lista por completitud del enunciado
    "Black-Litterman"    : w_bl,
    "Dynamic Programming": w_dynamic,
}

def max_drawdown_mensual(w):
    """MDD sobre la serie de riqueza generada por los retornos realizados."""
    r_p = ret.values @ w
    wealth = np.cumprod(1 + r_p)
    pico   = np.maximum.accumulate(wealth)
    dd     = wealth/pico - 1
    return dd.min()

filas = []
for nombre, w in portafolios.items():
    filas.append({
        "Portafolio": nombre,
        "Ret. anual": ret_port(w),
        "Vol anual" : vol_port(w),
        "Sharpe"    : sharpe_port(w),
        "Max DD"    : max_drawdown_mensual(w),
    })
tabla6 = pd.DataFrame(filas).set_index("Portafolio")
print(tabla6.to_string(formatters={
    "Ret. anual": pct, "Vol anual": pct, "Sharpe": "{:.3f}".format, "Max DD": pct}))

print("\nPesos por portafolio:")
pesos6 = pd.DataFrame({k: v for k, v in portafolios.items()}, index=activos)
print(pesos6.to_string(formatters={c: pct for c in pesos6.columns}))

# Gráfico comparativo de Sharpe (estilo de tu Portfolio_Optimization.ipynb)
fig, ax = plt.subplots(figsize=(8,4))
barras = ax.barh(tabla6.index, tabla6["Sharpe"],
                 color=["#5c85d6","#5ca85c","#9ac","#d6845c","#8e5cd6"])
ax.bar_label(barras, fmt="%.3f", padding=4)
ax.set_xlabel("Sharpe ratio"); ax.set_title("Sharpe por estrategia")
ax.invert_yaxis(); plt.tight_layout(); plt.show()

"""### 6.c — ¿Black-Litterman mejoró o empeoró la asignación?

Como no hubo vistas estadísticamente significativas en 2.c, el posterior BL
colapsa al equilibrio: $\mu_{BL} = \Pi$. Los pesos BL se obtienen optimizando
max-Sharpe sobre $\Pi$ en vez de la media muestral $\mu$, lo cual produce una
asignación más *shrunk hacia el mercado* y, en general, más diversificada.

Al comparar con el MVO restringido en la tabla 6:

- **Sharpe BL vs MVO restringido:** el Sharpe calculado con la media muestral
  full-sample favorece al MVO restringido, porque este fue optimizado
  directamente sobre $\mu$. Que BL tenga Sharpe menor in-sample no significa
  que sea un portafolio peor; simplemente que $\Pi \neq \mu$ y el max-Sharpe
  sobre $\Pi$ asigna de forma diferente.

- **Max DD:** el portafolio BL tiende a tener un drawdown menor o comparable
  porque los pesos de equilibrio están menos concentrados en los activos de
  mayor media histórica (que son también los más volátiles). Una asignación
  más repartida amortigua las caídas sincronizadas de mercado.

- **Conclusión:** BL "mejora" la robustez (menor riesgo de concentración en
  estimaciones ruidosas de $\mu$) a cambio de ceder algo de Sharpe in-sample.
  Con 11 años de datos y activos de mercados dispares, esa es la dirección
  correcta de la concesión.

### 6.d — Elección de portafolio (justificación)

El portafolio elegido es **Black-Litterman**. Los argumentos son:

1. **Robustez a la estimación:** la media muestral de 11 años de retornos
   mensuales tiene un error estándar de orden $\sigma/\sqrt{T} \approx 20\%/\sqrt{131} \approx 1.7\%$
   por activo. Optimizar max-Sharpe directamente sobre este estimador amplifica
   el error vía $\Sigma^{-1}$ (el efecto "error maximization" de Michaud). BL
   ancla las expectativas al equilibrio $\Pi$ y solo se desvía donde hay
   evidencia del forecasting — que en este caso no la hubo. Esto es una virtud,
   no una limitación.

2. **Consistencia con el análisis:** la sección 2.c mostró que ningún modelo
   predice retornos con superioridad estadística comprobable. Es consistente
   no inclinar el portafolio en ninguna dirección activa: confiar en el
   equilibrio es la conclusión correcta de un ejercicio riguroso.

3. **Contexto de mercado (jun-2026):** las valuaciones del SPY (P/E Shiller ≈ 43)
   y el riesgo político de BAP (balotaje peruano junio 2026) hacen especialmente
   valiosa la disciplina de los topes máximos (35% y 25% respectivamente).
   Los mismos topes aplican al portafolio BL, pero sus pesos son menos sensibles
   a una media histórica que puede no representar el régimen actual.

4. **La MVO sin restricciones se descarta** por producir posiciones cortas
   masivas y apalancamiento (sección 3.a), inviables en un mandato institucional.
   La MVO restringida es aceptable, pero usa $\mu$ directamente. El DP introduce
   una cobertura VAR que, aunque técnicamente válida, asigna 0% a LVMH por
   razones numéricas difíciles de justificar ante un comité de inversión.

Por estas razones, el portafolio BL es la elección más defendible: combina
equilibrio de mercado, disciplina estadística y las restricciones prácticas
ya justificadas en 3.b.
"""